services:
  db:
    image: mysql:latest
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: senhaSuperSegura
      MYSQL_DATABASE: coltec
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      mysql-phpmyadmin:
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db-mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: senhaSuperSegura
    networks:
      mysql-phpmyadmin:
    restart: always

volumes:
  db_data:
  
networks:
  mysql-phpmyadmin:
